/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "irtlmphajlhrzzqlgcwl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlydGxtcGhhamxocnp6cWxnY3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDMwNzQsImV4cCI6MjA2NDExOTA3NH0.SyyS63-e3ZWdyJIlzw3zJG9ojKwdNAmOV-30ZtGmLYU"